/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.6.4/userguide/building_java_projects.html
 */

plugins {
        kotlin("jvm") version "1.9.24"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}
 group="com.yit"
version="1.0-SNAPSHOT"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    implementation(kotlin("stdlib"))
    testImplementation("junit:junit:4.13.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:32.1.3-jre")
}

application {
    // Define the main class for the application.
    mainClass.set("com.yit.MainKt")
}
tasks.test {
 useJUnit() 
 testLogging { 
 events("passed", "failed", "skipped") 
 exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL  showStandardStreams = true 
 } 
 outputs.upToDateWhen { false } 
} 
java { 
 toolchain { 
 languageVersion.set(JavaLanguageVersion.of(17)) 
 } 
} 